/*
Copyright 2018 The Attic Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubeware/messenger/apis/messenger/v1alpha1"
	scheme "github.com/kubeware/messenger/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NotificationsGetter has a method to return a NotificationInterface.
// A group's client should implement this interface.
type NotificationsGetter interface {
	Notifications(namespace string) NotificationInterface
}

// NotificationInterface has methods to work with Notification resources.
type NotificationInterface interface {
	Create(*v1alpha1.Notification) (*v1alpha1.Notification, error)
	Update(*v1alpha1.Notification) (*v1alpha1.Notification, error)
	UpdateStatus(*v1alpha1.Notification) (*v1alpha1.Notification, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Notification, error)
	List(opts v1.ListOptions) (*v1alpha1.NotificationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Notification, err error)
	NotificationExpansion
}

// notifications implements NotificationInterface
type notifications struct {
	client rest.Interface
	ns     string
}

// newNotifications returns a Notifications
func newNotifications(c *MessengerV1alpha1Client, namespace string) *notifications {
	return &notifications{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the notification, and returns the corresponding notification object, and an error if there is any.
func (c *notifications) Get(name string, options v1.GetOptions) (result *v1alpha1.Notification, err error) {
	result = &v1alpha1.Notification{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("notifications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Notifications that match those selectors.
func (c *notifications) List(opts v1.ListOptions) (result *v1alpha1.NotificationList, err error) {
	result = &v1alpha1.NotificationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("notifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested notifications.
func (c *notifications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("notifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a notification and creates it.  Returns the server's representation of the notification, and an error, if there is any.
func (c *notifications) Create(notification *v1alpha1.Notification) (result *v1alpha1.Notification, err error) {
	result = &v1alpha1.Notification{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("notifications").
		Body(notification).
		Do().
		Into(result)
	return
}

// Update takes the representation of a notification and updates it. Returns the server's representation of the notification, and an error, if there is any.
func (c *notifications) Update(notification *v1alpha1.Notification) (result *v1alpha1.Notification, err error) {
	result = &v1alpha1.Notification{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("notifications").
		Name(notification.Name).
		Body(notification).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *notifications) UpdateStatus(notification *v1alpha1.Notification) (result *v1alpha1.Notification, err error) {
	result = &v1alpha1.Notification{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("notifications").
		Name(notification.Name).
		SubResource("status").
		Body(notification).
		Do().
		Into(result)
	return
}

// Delete takes name of the notification and deletes it. Returns an error if one occurs.
func (c *notifications) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("notifications").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *notifications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("notifications").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched notification.
func (c *notifications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Notification, err error) {
	result = &v1alpha1.Notification{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("notifications").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
